name: Automated assignment check
run-name: Your submission is being scored
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "*:homework/**"
jobs:
  homework-checker-infra:
    runs-on: ubuntu-22.04
    steps:
      - run: "echo 'REF: $GITHUB_REF, REF_NAME: $GITHUB_REF_NAME'"
