name: Automated assignment check
run-name: Your submission is being scored
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "*:homework/**"
jobs:
  homework-checker-infra:
    runs-on: ubuntu-latest
    steps:
      - run: echo "REF: $GITHUB_REF, REF_NAME: $GITHUB_REF_NAME, HEAD_REF	: $GITHUB_HEAD_REF, REPOSITORY: $GITHUB_REPOSITORY, REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER"
    
