name: Automated assignment check
run-name: Your submission is being scored
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "*:homework/**"
jobs:
  homework-checker-infra:
    runs-on: ubuntu-22.04
    container: python:3.9.15
    
    steps:
      - run: 'echo "REF: $GITHUB_REF, REF_NAME: $GITHUB_REF_NAME, HEAD_REF	: $GITHUB_HEAD_REF, REPOSITORY: $GITHUB_REPOSITORY, REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER"'
      - run: python --version
